# Generated by Django 5.2.7 on 2025-11-04 22:47

from django.db import migrations, models

def create_default_categories(apps, schema_editor):
	Category = apps.get_model("app", "Category")
	defaults = [
		{"name": "Food", "color": "#2ecc71", "type": "expense"},
		{"name": "Rent", "color": "#e74c3c", "type": "expense"},
		{"name": "Salary", "color": "#3498db", "type": "income"},
		{"name": "Entertainment", "color": "#9b59b6", "type": "expense"},
		{"name": "Transport", "color": "#f1c40f", "type": "expense"},
	]
	for cat in defaults:
		Category.objects.create(
			name=cat["name"],
			color=cat["color"],
			type=cat["type"],
			predefined=True
		)


class Migration(migrations.Migration):

	dependencies = [
		('app', '0002_category_color_category_predefined_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='category',
			name='type',
			field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=7),
		),
		migrations.RunPython(create_default_categories)
	]
